import * as archiverModule from "archiver";
import { Document, HeadingLevel, Packer, Paragraph } from "docx";
import { createRequire } from "node:module";
import PDFDocument from "pdfkit";

export type ArtifactFormat = "zip" | "pdf" | "docx" | "txt";
export type ProjectFile = { path: string; content: string };
export type ProjectPreviewFile = { path: string; content: string; truncated: boolean; lineCount: number };
type ArchiveWriter = {
  on: (event: "data" | "warning" | "error" | "end", listener: (...args: any[]) => void) => ArchiveWriter;
  append: (content: string, options: { name: string }) => void;
  finalize: () => Promise<void>;
};
const ZipArchiveConstructor = (archiverModule as unknown as { ZipArchive: new (options: { zlib: { level: number } }) => ArchiveWriter }).ZipArchive;
const resolvePackage = createRequire(import.meta.url);
const arabicPdfFontPath = resolvePackage.resolve("@fontsource/noto-naskh-arabic/files/noto-naskh-arabic-arabic-400-normal.woff");

export function safeArtifactSlug(value: string, fallback = "harb-output") {
  const slug = value
    .normalize("NFKD")
    .replace(/[^a-zA-Z0-9\u0600-\u06FF._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 96);
  return (slug || fallback).normalize("NFC");
}

export function normalizeProjectFilePath(value: string) {
  const path = value.trim().replace(/\\/g, "/").replace(/^\/+/, "");
  if (!path || path.includes("\0") || path.split("/").some(part => !part || part === "." || part === "..")) return null;
  if (path.length > 180 || path.startsWith(".env") || path.includes("/.env")) return null;
  return path;
}

export function normalizeProjectFiles(files: ProjectFile[]) {
  const normalized = new Map<string, string>();
  for (const file of files.slice(0, 16)) {
    const path = normalizeProjectFilePath(file.path);
    if (!path) continue;
    const content = file.content.slice(0, 90_000);
    if (!normalized.has(path)) normalized.set(path, content);
  }
  if (!normalized.has("README.md")) normalized.set("README.md", "# Harb technical project\n\nGenerated by Harb under owner governance.\n");
  return Array.from(normalized.entries()).map(([path, content]) => ({ path, content }));
}

export function createProjectPreview(files: ProjectFile[], maxFileBytes = 18_000) {
  return normalizeProjectFiles(files).map(file => {
    const content = file.content.slice(0, maxFileBytes);
    return {
      path: file.path,
      content,
      truncated: content.length < file.content.length,
      lineCount: file.content.split("\n").length,
    } satisfies ProjectPreviewFile;
  });
}

export async function createProjectArchive(files: ProjectFile[]) {
  const safeFiles = normalizeProjectFiles(files);
  return new Promise<Buffer>((resolve, reject) => {
    const archive = new ZipArchiveConstructor({ zlib: { level: 9 } });
    const chunks: Buffer[] = [];
    archive.on("data", (chunk: Buffer) => chunks.push(chunk));
    archive.on("warning", (error: Error) => { if ((error as NodeJS.ErrnoException).code !== "ENOENT") reject(error); });
    archive.on("error", reject);
    archive.on("end", () => resolve(Buffer.concat(chunks)));
    for (const file of safeFiles) archive.append(file.content, { name: file.path });
    void archive.finalize();
  });
}

function asParagraphs(content: string) {
  return content
    .replace(/\r\n/g, "\n")
    .split(/\n{2,}/)
    .filter(Boolean)
    .slice(0, 160)
    .map(part => new Paragraph({ text: part.replace(/^#{1,6}\s*/gm, "").trim(), spacing: { after: 180 } }));
}

async function createDocx(title: string, content: string) {
  const document = new Document({
    sections: [{
      properties: {},
      children: [new Paragraph({ text: title, heading: HeadingLevel.TITLE }), ...asParagraphs(content)],
    }],
  });
  return Buffer.from(await Packer.toBuffer(document));
}

function createPdf(title: string, content: string) {
  return new Promise<Buffer>((resolve, reject) => {
    const document = new PDFDocument({ size: "A4", margin: 52, info: { Title: title, Author: "Harb" } });
    const chunks: Buffer[] = [];
    document.on("data", (chunk: Buffer) => chunks.push(chunk));
    document.on("error", reject);
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.registerFont("HarbArabic", arabicPdfFontPath);
    document.font("HarbArabic").fontSize(18).fillColor("#122033").text(title, { align: "right" });
    document.moveDown();
    document.fontSize(12).fillColor("#27374A").text(content.replace(/#+\s?/g, ""), { lineGap: 4, align: /[\u0600-\u06FF]/.test(content) ? "right" : "left" });
    document.end();
  });
}

export async function createDocumentArtifact(title: string, content: string, format: Exclude<ArtifactFormat, "zip">) {
  if (format === "txt") return Buffer.from(`${title}\n\n${content}\n`, "utf8");
  if (format === "docx") return createDocx(title, content);
  return createPdf(title, content);
}

export const artifactMimeTypes: Record<ArtifactFormat, string> = {
  zip: "application/zip",
  pdf: "application/pdf",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  txt: "text/plain; charset=utf-8",
};
