import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { Beaker, BookOpenCheck, BrainCircuit, FilePlus2, Gauge, Loader2, Plus, Target } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const categoryLabels: Record<string, string> = { cyber_analysis: "تحليل سيبراني", authorization_decisions: "قرارات التفويض", document_analysis: "تحليل مستندات", code_review: "مراجعة كود", custom: "مخصص" };
const classifications: Record<string, string> = { private: "خاص", restricted: "مقيّد", shared: "مشترك" };
const publicSourceLabels = { cisa_kev: "CISA KEV — أولوية الثغرات المستغلة", nvd: "NVD — بيانات CVE/CPE المنظمة", mitre_attack: "MITRE ATT&CK — تصنيف المعرفة الدفاعية", owasp_wstg: "OWASP WSTG — منهج اختبار الويب" } as const;

function ObjectiveDialog({ onSaved }: { onSaved: () => void }) {
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [category, setCategory] = useState<"cyber_analysis" | "authorization_decisions" | "document_analysis" | "code_review" | "custom">("cyber_analysis");
  const [description, setDescription] = useState("");
  const [successCriteria, setSuccessCriteria] = useState("");
  const mutation = trpc.harb.lab.objectives.create.useMutation({ onSuccess: () => { toast.success("تمت إضافة هدف تطوير قابل للقياس."); setOpen(false); setTitle(""); setDescription(""); setSuccessCriteria(""); onSaved(); }, onError: error => toast.error(error.message) });
  const submit = () => { if (title.length < 3 || description.length < 10 || successCriteria.length < 10) return toast.error("أدخل هدفاً ووصفاً ومعيار نجاح واضحاً."); mutation.mutate({ title, category, description, successCriteria }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl bg-primary text-primary-foreground"><Plus className="ml-2 h-4 w-4" />هدف جديد</Button></DialogTrigger><DialogContent className="border-white/10 bg-[#152130] text-foreground sm:max-w-xl" dir="rtl"><DialogHeader><DialogTitle>هدف تطوير جديد</DialogTitle><DialogDescription>حوّل «التفوّق» إلى هدف محدد يمكن تقييمه على حالات مصرح بها.</DialogDescription></DialogHeader><div className="grid gap-3"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="مثال: تفسير تنبيهات أمنية عربية" /><select value={category} onChange={event => setCategory(event.target.value as typeof category)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">{Object.entries(categoryLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="ما المهمة والسياق والحدود؟" /><Textarea value={successCriteria} onChange={event => setSuccessCriteria(event.target.value)} placeholder="كيف تقيس النتيجة؟ مثال: دقة 90% مع سبب قابل للتدقيق." /></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>إلغاء</Button><Button onClick={submit} disabled={mutation.isPending}>{mutation.isPending && <Loader2 className="ml-2 h-4 w-4 animate-spin" />}حفظ الهدف</Button></DialogFooter></DialogContent></Dialog>;
}

function CollectionDialog({ onSaved }: { onSaved: () => void }) {
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [classification, setClassification] = useState<"private" | "restricted" | "shared">("private");
  const mutation = trpc.harb.lab.collections.create.useMutation({ onSuccess: () => { toast.success("تم إنشاء مجموعة معرفة جديدة."); setOpen(false); setName(""); setDescription(""); onSaved(); }, onError: error => toast.error(error.message) });
  const submit = () => { if (name.length < 3 || description.length < 10) return toast.error("أدخل اسم المجموعة ووصف استخدامها المصرح به."); mutation.mutate({ name, description, classification }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="border-white/15 bg-white/5"><BookOpenCheck className="ml-2 h-4 w-4" />مجموعة معرفة</Button></DialogTrigger><DialogContent className="border-white/10 bg-[#152130] text-foreground sm:max-w-xl" dir="rtl"><DialogHeader><DialogTitle>مجموعة معرفة مصرح بها</DialogTitle><DialogDescription>يحفظ Harb مرجع الملف وبياناته الوصفية؛ ولا يبدأ الفهرسة أو التدريب قبل مراجعة المصدر.</DialogDescription></DialogHeader><div className="grid gap-3"><Input value={name} onChange={event => setName(event.target.value)} placeholder="اسم مجموعة المعرفة" /><select value={classification} onChange={event => setClassification(event.target.value as typeof classification)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">{Object.entries(classifications).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="الغرض والمالك والقيود وحقوق الاستخدام." /></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>إلغاء</Button><Button onClick={submit} disabled={mutation.isPending}>{mutation.isPending && <Loader2 className="ml-2 h-4 w-4 animate-spin" />}حفظ المجموعة</Button></DialogFooter></DialogContent></Dialog>;
}

export function ModelLabPanel() {
  const utils = trpc.useUtils();
  const lab = trpc.harb.lab.dashboard.useQuery();
  const models = trpc.harb.lab.models.useQuery(undefined, { retry: false });
  const [selectedCollection, setSelectedCollection] = useState("");
  const [selectedFile, setSelectedFile] = useState("");
  const [selectedPublicSource, setSelectedPublicSource] = useState<keyof typeof publicSourceLabels>("cisa_kev");
  const [evaluationObjective, setEvaluationObjective] = useState("");
  const [evaluationCollection, setEvaluationCollection] = useState("");
  const [modelId, setModelId] = useState("");
  const [evaluationNotes, setEvaluationNotes] = useState("");
  const refresh = () => void utils.harb.lab.dashboard.invalidate();
  const registerSource = trpc.harb.lab.sources.registerWorkspaceFile.useMutation({ onSuccess: () => { toast.success("تم تسجيل المصدر بانتظار الفهرسة والمراجعة."); setSelectedFile(""); refresh(); }, onError: error => toast.error(error.message) });
  const registerPublicSource = trpc.harb.lab.sources.registerPublicReference.useMutation({ onSuccess: () => { toast.success("تم تسجيل المرجع العام للتقييم فقط؛ لم تُجرَ أي فهرسة تلقائية."); refresh(); }, onError: error => toast.error(error.message) });
  const createEvaluation = trpc.harb.lab.evaluations.create.useMutation({ onSuccess: () => { toast.success("تم إعداد تجربة التقييم. أضف حالات اختبار مصرح بها لبدئها."); setEvaluationNotes(""); refresh(); }, onError: error => toast.error(error.message) });
  const data = lab.data;
  const objectives = data?.objectives ?? [];
  const collections = data?.collections ?? [];
  const sources = data?.sources ?? [];
  const evaluations = data?.evaluations ?? [];
  const files = data?.files ?? [];
  const addSource = () => { if (!selectedCollection || !selectedFile) return toast.error("اختر مجموعة معرفة وملفاً من مساحة العمل."); registerSource.mutate({ collectionId: selectedCollection, workspaceFileId: selectedFile }); };
  const addPublicSource = () => { if (!selectedCollection) return toast.error("اختر مجموعة معرفة قبل تسجيل المرجع العام."); registerPublicSource.mutate({ collectionId: selectedCollection, sourceId: selectedPublicSource }); };
  const draftEvaluation = () => { if (!evaluationObjective || !modelId.trim()) return toast.error("اختر هدفاً وأدخل معرف نموذج من الكتالوج المتاح."); createEvaluation.mutate({ objectiveId: evaluationObjective, collectionId: evaluationCollection || undefined, modelId: modelId.trim(), notes: evaluationNotes || undefined }); };

  return <section id="lab" className="mt-7 scroll-mt-6"><div className="rounded-2xl border border-violet-300/15 bg-gradient-to-l from-violet-400/10 via-[#192032]/90 to-[#111a26]/90 p-5 sm:p-7"><div className="flex flex-col gap-4 border-b border-white/10 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker text-violet-200">Model Improvement Lab</p><h2 className="mt-1 text-2xl font-bold">مختبر تطوير النموذج</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">ضع المهام القابلة للقياس، واربط المعرفة المصرح بها، ثم صمّم تجربة تقييم قبل أي ضبط دقيق أو تدريب مخصص.</p></div><div className="flex flex-wrap gap-2"><CollectionDialog onSaved={refresh} /><ObjectiveDialog onSaved={refresh} /></div></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><div className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-center justify-between"><div><p className="section-kicker">Objectives</p><h3 className="mt-1 font-bold">مهام ومعايير نجاح</h3></div><Badge variant="outline" className="border-violet-200/20 text-violet-200">{objectives.length} أهداف</Badge></div><div className="mt-4 max-h-72 space-y-2 overflow-y-auto">{objectives.length ? objectives.map(item => <article key={item.id} className="rounded-xl border border-white/8 bg-background/40 p-3"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.title}</p><Badge variant="outline" className="border-white/10 text-[10px] text-muted-foreground">{categoryLabels[item.category]}</Badge></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.description}</p><p className="mt-2 rounded-lg border border-violet-200/10 bg-violet-400/5 p-2 text-[11px] leading-5 text-violet-100">معيار النجاح: {item.successCriteria}</p></article>) : <div className="rounded-xl border border-dashed border-white/15 p-6 text-center"><Target className="mx-auto h-6 w-6 text-muted-foreground" /><p className="mt-2 text-sm font-medium">لم تحدد مهاماً بعد</p><p className="mt-1 text-xs text-muted-foreground">ابدأ بأهم مهمة سيبرانية تريد تحسينها وقِس نجاحها.</p></div>}</div></div>
      <div className="rounded-2xl border border-violet-200/15 bg-violet-400/5 p-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-300/10 text-violet-200"><BrainCircuit className="h-5 w-5" /></span><div><p className="section-kicker text-violet-200">Knowledge Registry</p><h3 className="mt-1 font-bold">ربط مصدر معرفة من مساحة العمل</h3></div></div><div className="mt-5 grid gap-3"><select value={selectedCollection} onChange={event => setSelectedCollection(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">اختر مجموعة معرفة</option>{collections.map(item => <option key={item.id} value={item.id}>{item.name} — {classifications[item.classification]}</option>)}</select><select value={selectedFile} onChange={event => setSelectedFile(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">اختر ملفاً من مساحة العمل</option>{files.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Button onClick={addSource} disabled={registerSource.isPending} className="bg-violet-300 text-violet-950 hover:bg-violet-200">{registerSource.isPending ? <Loader2 className="ml-2 h-4 w-4 animate-spin" /> : <FilePlus2 className="ml-2 h-4 w-4" />}تسجيل المصدر</Button></div><p className="mt-3 text-xs leading-5 text-muted-foreground">يبقى المصدر في حالة «مسجل» حتى يتم فحص نوع الملف وحقوق الاستخدام وتحضير فهرسة آمنة.</p><div className="mt-4 border-t border-white/10 pt-4"><p className="text-xs font-semibold text-violet-100">مرجع عام موثق للتقييم فقط</p><div className="mt-2 grid gap-2 sm:grid-cols-[1fr_auto]"><select value={selectedPublicSource} onChange={event => setSelectedPublicSource(event.target.value as keyof typeof publicSourceLabels)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">{Object.entries(publicSourceLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><Button onClick={addPublicSource} disabled={registerPublicSource.isPending} variant="outline" className="border-violet-200/25 text-violet-100 hover:bg-violet-300/10">{registerPublicSource.isPending && <Loader2 className="ml-2 h-4 w-4 animate-spin" />}تسجيل المرجع</Button></div><p className="mt-2 text-[11px] leading-5 text-muted-foreground">يُحفظ الرابط وملاحظة الترخيص فقط. راجع شروط المصدر قبل تنزيله أو فهرسته أو استخدامه في تدريب.</p></div></div></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-center justify-between"><div><p className="section-kicker">Sources</p><h3 className="mt-1 font-bold">مصادر المعرفة المسجلة</h3></div><BookOpenCheck className="h-5 w-5 text-violet-200" /></div><div className="mt-4 space-y-2">{sources.length ? sources.slice(0, 8).map(source => <article key={source.id} className="rounded-xl border border-white/8 bg-background/40 p-3"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium">{source.name}</p><Badge className="border border-amber-200/20 bg-amber-300/10 text-[10px] text-amber-200">{source.indexingStatus === "registered" ? "بانتظار الفهرسة" : source.indexingStatus}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{source.mimeType ?? "نوع غير محدد"} · {source.chunkCount} مقاطع جاهزة</p></article>) : <p className="rounded-xl border border-dashed border-white/15 p-5 text-center text-xs text-muted-foreground">لا توجد مصادر معرفة مسجلة.</p>}</div></div>
      <div className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Gauge className="h-5 w-5" /></span><div><p className="section-kicker">Evaluation Gate</p><h3 className="mt-1 font-bold">إعداد تجربة تقييم</h3></div></div><div className="mt-5 grid gap-3"><select value={evaluationObjective} onChange={event => setEvaluationObjective(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">اختر هدفاً</option>{objectives.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select value={evaluationCollection} onChange={event => setEvaluationCollection(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">مجموعة معرفة اختيارية</option>{collections.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input value={modelId} onChange={event => setModelId(event.target.value)} list="harb-model-catalog" placeholder="معرف النموذج من الكتالوج المتاح" /><datalist id="harb-model-catalog">{models.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</datalist><Textarea value={evaluationNotes} onChange={event => setEvaluationNotes(event.target.value)} placeholder="ملاحظات الاختبار، نوع الحالات، أو ضوابط البيانات." /><Button onClick={draftEvaluation} disabled={createEvaluation.isPending} className="bg-primary text-primary-foreground">{createEvaluation.isPending ? <Loader2 className="ml-2 h-4 w-4 animate-spin" /> : <Beaker className="ml-2 h-4 w-4" />}إعداد تجربة تقييم</Button></div><p className="mt-3 text-xs leading-5 text-muted-foreground">لا تُشغّل التجربة في هذه المرحلة: تحتاج حالات اختبار صالحة ومصرحاً بها قبل تشغيل أي استدعاءات نموذجية.</p></div></div>
    <div className="mt-6 rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-center justify-between"><div><p className="section-kicker">Evaluation Ledger</p><h3 className="mt-1 font-bold">تجارب التقييم</h3></div><Badge variant="outline" className="border-white/10 text-muted-foreground">{evaluations.length} مسودات</Badge></div><div className="mt-4 space-y-2">{evaluations.length ? evaluations.map(item => <article key={item.id} className="flex flex-col gap-2 rounded-xl border border-white/8 bg-background/40 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{item.modelId}</p><p className="mt-1 text-xs text-muted-foreground">حالات: {item.sampleCount} · مجتاز: {item.passedCount} · النتيجة: {item.score ?? "لم تبدأ"}</p></div><Badge className={cn("border text-[10px]", item.status === "completed" ? "border-primary/20 bg-primary/10 text-primary" : "border-amber-200/20 bg-amber-300/10 text-amber-200")}>{item.status === "draft" ? "تحتاج حالات اختبار" : item.status}</Badge></article>) : <p className="rounded-xl border border-dashed border-white/15 p-5 text-center text-xs text-muted-foreground">أنشئ تجربة بعد تحديد الهدف ومصدر المعرفة والنموذج.</p>}</div></div>
  </div></section>;
}
